################################################################################
# This file contains the configuration for the cortex-annotate toolkit. By
# editing this file, one can configure cortex-annotate to work with various
# datasets and to enable annotation of specific contours, points, and
# boundaries.

display:
  figsize: [4, 4]
  dpi: 128
  active_style:
    color: [0.97, 0.97, 0.97]
    markersize: 4
  default_style:
    color: [0.55, 0.55, 0.9]
    markersize: 0
    linewidth: 2
    linestyle: "solid"
    

init: |
  # Load libraries that will be used throughout the configuration file.
  import re
  import glob
  import numpy as np
  import os.path as op
  import neuropythy as ny
  from struct import unpack
  from matplotlib.colors import LinearSegmentedColormap
  from neuropythy.geometry.util import barycentric_to_cartesian

  # define dataset directory (inside Docker container)
  datasets_dir = op.join("/home", "jovyan", "datasets") 
  
  # define flatmap kwargs
  FLATMAP_KWARGS = {
    "mask"      : ( "parcellation", 43 ), 
    "map_right" : "right",
    "radius"    : np.pi / 2
  }

  # load fsaverage as a subject object
  fsa = ny.freesurfer_subject("fsaverage")

  # prepare fsaverage cortex
  fsa_cortex = {} # initialize
  fsa_cortex["lh"] = fsa.hemis["lh"].copy()
  fsa_cortex["rh"] = fsa.hemis["rh"].copy()

  # prepare fsaverage flatmaps
  fsa_flatmap = {} # initialize
  fsa_flatmap["lh"] = fsa_cortex["lh"].mask_flatmap(**FLATMAP_KWARGS)
  fsa_flatmap["rh"] = fsa_cortex["rh"].mask_flatmap(**FLATMAP_KWARGS)

  # initalize search tree for flatmap address lookup (see canvas_to_viewer)
  fsa_flatmap["lh"].address(np.array([[0, 0]]))
  fsa_flatmap["rh"].address(np.array([[0, 0]]))

  # define function to read participant (packed) data files
  def read_property(filename):
      with open(filename, "rb") as f:
          values = f.read() # load file content
          fstr = "e" * (len(values) // 2)
          values = np.array(unpack(fstr, values))
      return values

  # define a custom colormap for isoeccentricity figures
  edge_cmap = LinearSegmentedColormap.from_list(
    name = "edge", 
    colors = [
      (0, (0, 1, 1)),    # negative values begin at cyan
      (0.49, (0, 0, 0)), # black edge, just before the threshold value
      (0.50, (1, 1, 0)), # yellow edge, at the threshold value
      (0.51, (1, 1, 1)), # white edge, just after the threshold value
      (1, (1, 0, 0))     # positive values go towards red
    ]
  )

  # define isoeccentricity list
  isoeccentricity_list = ( 0.5, 1.0, 2.0, 4.0, 7.0, 11.0 )
  isoeccentricity_dict = {
    f"eccen_{iso}": { "func": lambda prop, _: { f"eccen_{iso}": prop }, 
                      "kwargs": { "cmap": edge_cmap, "vmin": -1, "vmax": 1 } } 
    for iso in isoeccentricity_list 
  }

  # define the propety kwargs for each property
  PROPERTY_KWARGS = {
    "angle"     : { "func": lambda prop, h: { f"polar_angle_{h}": prop }, 
                    "kwargs": { } },
    "eccen"     : { "func": lambda prop, _: { "eccentricity": prop }, 
                    "kwargs": { } },
    "vexpl"     : { "func": lambda prop, _: prop, 
                    "kwargs": { "cmap": "hot", "vmin": 0, "vmax": 100 } },
    "curvature" : { "func": lambda prop, _: None, 
                    "kwargs": { "underlay": "curvature" } },
    **isoeccentricity_dict
  }


targets:
  # The "Dataset" is a choice for the user; as a list of one option.
  Dataset:
    - CHN-Retinotopy
    - HCP-Retinotopy
    - NOD
    - NSD
    - NYU-Retinotopy
    - StudyForrest

  # The "Participant" is a choice for the user. It will depend on the dataset
  # selection, so we define it as a function returning the list of participants.
  Participant: 
    depends_on: Dataset
    calculate: |
      # get dropdown selection from above choices.
      dataset = target["Dataset"].lower() # string

      # define dataset directory
      dataset_dir = op.join(datasets_dir, dataset)

      # find all participant directories in dataset directory
      participant_dirs = glob.glob(op.join(dataset_dir, "*"))

      # extract participant names from participant directories
      participants = [op.basename(d) for d in participant_dirs]

      # return list of participants for dropdown menu
      return participants

  # The "Hemisphere" is a choice for the user; as a list of two options.
  Hemisphere:
    - Left Hemisphere
    - Right Hemisphere

  # create the participant cortex object.
  cortex: |
    # get dropdown selections from above choices.
    dataset     = target["Dataset"].lower() # string
    participant = target["Participant"]     # string
    hemisphere  = target["Hemisphere"]      # string

    # Format dropdown items
    fs_hemi = f"{hemisphere[0].lower()}h"

    # Define participant directory
    participant_dir = op.join(datasets_dir, dataset, participant)

    # find all participant property files
    prop_files = glob.glob(op.join(participant_dir, f"{fs_hemi}.3d.*"))

    # Load participant midgray coordinates
    coordinates_file = [x for x in prop_files if x.endswith("coordinates")][0]
    coordinates = read_property(coordinates_file).reshape((3, -1))

    # Create participant midgray mesh
    midgray_mesh = ny.geometry.Mesh(
      faces       = fsa_cortex[fs_hemi].tess, 
      coordinates = coordinates
    )

    # Load remaining property files
    property_files = [x for x in prop_files if x != coordinates_file]
    props = {
      fname.split(".")[-1]: read_property(fname).reshape((-1, ))
      for fname in property_files
    }

    # Calculate the isoeccentricity maps
    for isoeccentricity in isoeccentricity_list:
      # Define property name for the current isoeccentricity
      prop_name = f"eccen_{isoeccentricity}"

      # Compute values relative to threshold 
      # (clipped to [0, 16] eccentricity to remove extreme outliers)
      values = np.clip(props["eccen"].copy(), 0, 16)
      values = values - isoeccentricity
  
      # Normalize negative values to [-1, 0]
      negative_index = values < 0
      values[negative_index] = (values[negative_index] /
        np.abs(np.nanmin(values[negative_index])))

      # Normalize positive values to [0, 1]
      positive_index = values > 0
      values[positive_index] = (values[positive_index] / 
        np.nanmax(values[positive_index]))

      # Store values in props dictionary
      props[prop_name] = values

    # Create participant cortex object
    participant_cortex = fsa_cortex[fs_hemi].copy()
    participant_cortex = ny.mri.Cortex(
      chirality = fs_hemi, 
      tess      = participant_cortex.tess,
      surfaces  = { 
        **participant_cortex.surfaces, 
        **{ "midgray": midgray_mesh }
      },
      registrations = participant_cortex.registrations, 
      properties    = props
    )
  
    # Return participant cortex with properties
    return participant_cortex

  # create participant flatmap.
  flatmap: |
    # get dropdown selections from above choices.
    cortex = target["cortex"] # cortex object created above
    
    # Create participant flatmap 
    participant_flatmap = cortex.mask_flatmap(**FLATMAP_KWARGS)

    # Return participant flatmap 
    return participant_flatmap


annotations:
  # V1 contours:
  V1 Foveal Point:
    type: point
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  V1 UVM (ventral):
    fixed_head: V1 Foveal Point
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  V1 LVM (dorsal):
    fixed_head: V1 Foveal Point
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  V1 Periphery:
    fixed_head: V1 UVM (ventral)
    fixed_tail: V1 LVM (dorsal)
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  # V2 contours:
  V2 Foveal Point:
    type: point
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  V2 UVM (ventral):
    fixed_head: V2 Foveal Point
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  V2 LVM (dorsal):
    fixed_head: V2 Foveal Point
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  V2 Ventral Periphery:
    fixed_head: V2 UVM (ventral)
    fixed_tail: V1 UVM (ventral)
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  V2 Dorsal Periphery:
    fixed_head: V2 LVM (dorsal)
    fixed_tail: V1 LVM (dorsal)
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  # V3 contours:
  V3 Foveal Point:
    type: point
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  V3 UVM (ventral):
    fixed_head: V3 Foveal Point
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  V3 LVM (dorsal):
    fixed_head: V3 Foveal Point
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  V3 Ventral Periphery:
    fixed_head: V3 UVM (ventral)
    fixed_tail: V2 UVM (ventral)
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  V3 Dorsal Periphery:
    fixed_head: V3 LVM (dorsal)
    fixed_tail: V2 LVM (dorsal)
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  # hV4 contour:
  hV4 Outer:
    type: contour
    fixed_head: V3 Foveal Point
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  # VO contour:
  VO Outer:
    type: contour
    fixed_head: V3 UVM (ventral)
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  # hV4|VO boundary:
  hV4|VO Boundary:
    type: contour
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  # VO1|2 boundary:
  VO1|2 Boundary: 
    type: contour
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  # V3a|b contours:
  V3a|b Outer:
    type: contour
    fixed_head: V3 LVM (dorsal)
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  V3a|b Inner Boundary:
    type: contour
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  # IPS0 Outer:
  IPS0 Outer:
    type: contour
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  # LO1 Outer:
  LO1 Outer:
    type: contour
    fixed_head: V3 Foveal Point
    figure_grid:
      - ["angle", "eccen"]
      - ["curvature", "vexpl"]
  # Isoecentricity contours:
  0.5 Degrees Eccentricity:
    type: contour
    figure_grid:
      - ["eccen_0.5", "angle"]
      - ["eccen", "vexpl"]
  1.0 Degrees Eccentricity:
    type: contour
    figure_grid:
      - ["eccen_1.0", "angle"]
      - ["eccen", "vexpl"]
  2.0 Degrees Eccentricity:
    type: contour
    figure_grid:
      - ["eccen_2.0", "angle"]
      - ["eccen", "vexpl"]
  4.0 Degrees Eccentricity:
    type: contour
    figure_grid:
      - ["eccen_4.0", "angle"]
      - ["eccen", "vexpl"]
  7.0 Degrees Eccentricity:
    type: contour
    figure_grid:
      - ["eccen_7.0", "angle"]
      - ["eccen", "vexpl"]
    filter: |
      return target["Dataset"] != "NSD"
  11.0 Degrees Eccentricity:
    type: contour
    figure_grid:
      - ["eccen_11.0", "angle"]
      - ["eccen", "vexpl"]
    filter: |
      return target["Dataset"] in ( "NYU-Retinotopy", )


figures:
  _: |
    # prepare (formatted) target information for figure code below
    hemisphere = target["Hemisphere"]  # string
    fs_hemi    = f"{hemisphere[0].lower()}h"

    # prepare property values for figure
    values = target["flatmap"].properties[key]

    # get property function and kwargs for angle property
    prop_color  = PROPERTY_KWARGS[key]["func"](values, fs_hemi)
    prop_kwargs = PROPERTY_KWARGS[key]["kwargs"]

    ny.cortex_plot(
      mesh = target["flatmap"], color = prop_color, axes = axes, **prop_kwargs
    )
  term: |
    # figure aesthetics and limits
    xy = target["flatmap"].coordinates
    (xmin, ymin) = np.min(xy, axis = 1)
    (xmax, ymax) = np.max(xy, axis = 1)
    axes.set_xlim((xmin, xmax))
    axes.set_ylim((ymin, ymax))


viewer:
  # Expected `faces` shape: [ n_faces, 3 ]
  faces: |
    return target["cortex"].tess.faces.T
  
  # Expected `coordinates` shape: [ n_vertices, xyz (3) ]
  coordinates: 
    midgray: |
      return target["cortex"].surfaces["midgray"].coordinates.T
    inflated: |
      return target["cortex"].surfaces["inflated"].coordinates.T
  
  # Must be have matching coordinates fields. 
  morph_between: [ "midgray", "inflated" ]

  # Expected overlay shape: [ n_vertices, rgb (3) ]
  overlays: 
    curvature: |
      # return curvature colors for cortical mesh plot
      return ny.graphics.cortex_plot_colors(target["cortex"])[:,:3]
    _: |
      # prepare (formatted) target information for figure code below
      hemisphere = target["Hemisphere"]  # string
      fs_hemi    = f"{hemisphere[0].lower()}h"

      # prepare colormap name and values for figure
      values = target["cortex"].properties[key]

      # get property function and kwargs for angle property
      prop_color  = PROPERTY_KWARGS[key]["func"](values, fs_hemi)
      prop_kwargs = PROPERTY_KWARGS[key]["kwargs"]

      # return vertex colors for cortical mesh plot
      return ny.graphics.cortex_plot_colors(target["cortex"], 
        color = prop_color, **prop_kwargs)[:,:3]
  
  # code to convert canvas (2d) coordinates to viewer (3d) coordinates, 
  # Input: `target` (as above), 
  #        `points` from canvas annotations (n_points, 2), and 
  #        `mesh_coordinates` (n_vertices, 3) 
  # Output: viewer coordinates (n_points, 3)
  canvas_to_viewer: |
    # prepare (formatted) target information for figure code below
    hemisphere = target["Hemisphere"]  # string
    fs_hemi    = f"{hemisphere[0].lower()}h"

    # convert canvas (2d) coordinates to barycentric coordinates
    flatmap_address  = fsa_flatmap[fs_hemi].address(points)
    bary_faces       = flatmap_address["faces"]       # (3, n_faces)
    bary_coordinates = flatmap_address["coordinates"] # (2, n_points)
    
    # sample barycentric coordinates on 3d mesh coordinates
    tx = mesh_coordinates[bary_faces] # (n_vertices, n_points, n_triangles)
    tx = np.transpose(tx, (0, 2, 1))  # (n_vertices, n_triangles, n_points)
    
    # return cartesian coordinates for each point along the mesh 
    return barycentric_to_cartesian(tx, bary_coordinates).T # (n_points, 3)